### ISSUE TITLE
Need help on below -- Not exactly a issue. 

### ISSUE THREAD

**Issue by rahulcse1** [kensiprell/grails-atmosphere-meteor-sample#22]
Hi Ken
In index.gsp . i replaced userName with session id. and open two client chrome and Firefox. it's establishing connection. but when i send notification .. it's not rendering on other client.
If i send from chrome , it's not rendering on FF client and vice versa.
Is there any way to push data to specific client. On page load i am establishing connection base on session id.
url=/atmosphere/notification/AA0F52F62C3E9152D4D69C92430BCE5B will be like this and it will be different for all user. Now i have send notification form one specific user to another.

**Comment by kensiprell** [comment]
I'm asusming you've cloned the repo and are making step-by-step changes to it. If the client is [subcribed](https://github.com/kensiprell/grails-atmosphere-meteor-sample/blob/master/grails-app/views/atmosphereTest/index.gsp#L187-L196) to the correct URL, could it be that you aren't sending the notifications to the correct client? You'll need some way on the server to keep track of the session IDs and retrieve those to send a message. For example, see the snippet below that could be in a controller or service:

```
def atmosphereMeteorService

someMethod(sessionID) {
    def mapping = "/atmosphere/notification/$sessionID"
    atmosphereMeteorService.broadcast(mapping, "This is a test.")
}

```

Does this answer your question?

Ken

**Comment by rahulcse1** [comment]
I'll try this one today. Thanks for your input :)

On Wed, Jan 13, 2016 at 3:05 PM, Ken Siprell <notifications@github.com>
wrote:

> I'm asusming you've cloned the repo and are making step-by-step changes to
> it. If the client is subcribed
> <https://github.com/kensiprell/grails-atmosphere-meteor-sample/blob/master/grails-app/views/atmosphereTest/index.gsp#L187-L196>
> to the correct URL, could it be that you aren't sending the notifications
> to the correct client? You'll need some way on the server to keep track of
> the session IDs and retrieve those to send a message. For example, see the
> snippet below that could be in a controller or service:
>
> def atmosphereMeteorService
>
> someMethod(sessionID) {
>     def mapping = "/atmosphere/notification/$sessionID"
>     atmosphereMeteorService.broadcast(mapping, "This is a test.")
> }
>
>
> Does this answer your question?
>
> Ken
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kensiprell/grails-atmosphere-meteor-sample/issues/22#issuecomment-171230531>
> .
>



-- 

Thanks & regards

Amarjeet Chauhan
http://www.techwalk.me/
M: +91-9640360270
