### ISSUE TITLE
Sample sendDisconnectMessage does not send message in chat broadcast

### ISSUE THREAD

**Issue by harbdog** [kensiprell/grails-atmosphere-meteor-sample#24]
I noticed this function doesn't actually send the "A user has left the chat  session" message to the clients still subscribed to the chat, when another client disconnects.  Modifying the function in AtmosphereTestService.groovy to the following code seems to have made it work:

	def sendDisconnectMessage(event, request) {
		// This method could be used to send chat participants a message that a user has left.
		def message = "A user has left the chat session"
		println message
        
		def finishedResponse = [type:"chat", message:message] as JSON
		String mapping = "/atmosphere/chat" + request.getPathInfo();
		atmosphereMeteorService.broadcast(mapping, finishedResponse)
	}

I couldn't seem to make it work at all using the event.broadcaster() way that is currently in the sample.

**Comment by harbdog** [comment]
I managed to get event.broadcaster() to broadcast successfully, just needed to put the message in a JSON map instead of passing the string message directly to broadcast:

	def sendDisconnectMessage(event, request) {
	    // This method could be used to send chat participants a message that a user has left.
	    def message = "A user has left the chat session"
	    println message
	
	    def finishedResponse = [type:"chat", message:message] as JSON
		event.broadcaster().broadcast(finishedResponse)
	}

**Comment by kensiprell** [comment]
Thanks, Eric. I didn't even realize that wasn't working. I fixed it with this [commit](https://github.com/kensiprell/grails-atmosphere-meteor-sample/commit/7eb8a9b4f2c89739af8f9794eba8f5a3a5f46694).
